#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_AXI_BRAM_CTRL_0_COMPATIBLE "xlnx,axi-bram-ctrl-4.1"
#define XPAR_AXI_BRAM_CTRL_0_BASEADDR 0xc0000000
#define XPAR_AXI_BRAM_CTRL_0_HIGHADDR 0xc0001fff
#define XPAR_AXI_BRAM_CTRL_0_BRAM_DATA_WIDTH 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_ECC_PRESENT 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_FAULT_INJECTION_PRESENT 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_CORRECTABLE_FAILING_REGISTERS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_CORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_UNCORRECTABLE_FAILING_REGISTERS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_UNCORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_ECC_STATUS_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_CORRECTABLE_COUNTER_BITS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_ECC_ON_OFF_REGISTER 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_ECC_ON_OFF_RESET_VALUE 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_WRITE_ACCESS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_MEM_BASE_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_MEM_HIGH_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_MEM_CTRL_BASE_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_MEM_CTRL_HIGH_ADDRESS 0x0

/* Canonical definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_XBRAM_0_BASEADDR 0xc0000000
#define XPAR_XBRAM_0_HIGHADDR 0xc0001fff
#define XPAR_XBRAM_0_BRAM_DATA_WIDTH 0x0
#define XPAR_XBRAM_0_BRAM_ECC_PRESENT 0x0
#define XPAR_XBRAM_0_BRAM_FAULT_INJECTION_PRESENT 0x0
#define XPAR_XBRAM_0_BRAM_CORRECTABLE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_BRAM_CORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_XBRAM_0_BRAM_UNCORRECTABLE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_BRAM_UNCORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_XBRAM_0_BRAM_ECC_STATUS_INTERRUPT_PRESENT 0x0
#define XPAR_XBRAM_0_BRAM_CORRECTABLE_COUNTER_BITS 0x0
#define XPAR_XBRAM_0_BRAM_ECC_ON_OFF_REGISTER 0x0
#define XPAR_XBRAM_0_BRAM_ECC_ON_OFF_RESET_VALUE 0x0
#define XPAR_XBRAM_0_BRAM_WRITE_ACCESS 0x0
#define XPAR_XBRAM_0_BRAM_MEM_BASE_ADDRESS 0x0
#define XPAR_XBRAM_0_BRAM_MEM_HIGH_ADDRESS 0x0
#define XPAR_XBRAM_0_BRAM_MEM_CTRL_BASE_ADDRESS 0x0
#define XPAR_XBRAM_0_BRAM_MEM_CTRL_HIGH_ADDRESS 0x0
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,axi-bram-ctrl-4.1"

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x1c200
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x1c200
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/* Definitions for peripheral MYIP_MAC_0 */
#define XPAR_MYIP_MAC_0_BASEADDR 0x20000
#define XPAR_MYIP_MAC_0_HIGHADDR 0x20fff

/* Canonical definitions for peripheral MYIP_MAC_0 */
#define XPAR_MYIP_MAC_0_BASEADDR 0x20000
#define XPAR_MYIP_MAC_0_HIGHADDR 0x20fff

/*  BOARD definition */
#define XPS_BOARD_ARTY-A7-100

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x1ffff
#define XPAR_AXI_BRAM_0_BASEADDRESS 0xc0000000
#define XPAR_AXI_BRAM_0_HIGHADDRESS 0xc0001fff

/*  CPU parameters definition */
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0
#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_RISCV_D_LMB 1
#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

#define STDOUT_BASEADDRESS 0x40600000
#define STDIN_BASEADDRESS 0x40600000

/* Device ID */
#define XPAR_DEVICE_ID "7a100t"

#endif  /* end of protection macro */